Repository owasp-modsecurity/ModSecurity, pull requests merged in 2024-02, with the labels that each got.

#2969 Double memory allocation
  apache2/re.c
Labels: 2.x

#3012 ctl:ruleRemoveByTag isn't executed if no rule id is present in the rule
  apache2/re.c
Labels: 2.x

#3004 Optimization: Avoid last loop and storing an empty value in case nothing after last %{..} macro
  apache2/re_actions.c
Labels: 2.x

#2994 Implement msre_action_phase_validate()
  apache2/re_actions.c
Labels: 2.x

#3080 test: Logical, syntax and cosmetic fixes on test cases
  test/test-cases/regression/action-ctl_rule_remove_by_id.json
  test/test-cases/regression/action-ctl_rule_remove_by_tag.json
  test/test-cases/regression/action-ctl_rule_remove_target_by_id.json
  test/test-cases/regression/action-ctl_rule_remove_target_by_tag.json
  test/test-cases/regression/issue-1850.json
  test/test-cases/regression/misc-variable-under-quotes.json
  test/test-cases/regression/rule-920200.json
Labels: 3.x

#3078 feat: Add more steps: install built module and restart the server
  .github/security2.conf
  .github/workflows/ci.yml
Labels: 2.x, new feature

#3094 fix: Replace obsolote macros
  build/compile
  build/find_apr.m4
  build/find_apu.m4
  build/find_curl.m4
  build/find_lua.m4
  build/find_pcre.m4
  build/find_pcre2.m4
  build/find_ssdeep.m4
  build/find_yajl.m4
  configure.ac
Labels: 2.x

#3095 fix: Replace obsolete macros
  build/lua.m4
  build/pcre.m4
  configure.ac
Labels: 3.x

#3079 Bump the C++ version from C++11 to C++17
  README.md
  configure.ac
  examples/reading_logs_via_rule_message/Makefile.am
  examples/reading_logs_with_offset/Makefile.am
  examples/using_bodies_in_chunks/Makefile.am
  src/Makefile.am
  src/parser/Makefile.am
  test/Makefile.am
  test/benchmark/Makefile.am
  test/fuzzer/Makefile.am
  tools/rules-check/Makefile.am
Labels: 3.x

#3096 Clean up 'return' never will be executed.
  examples/reading_logs_via_rule_message/reading_logs_via_rule_message.h
  examples/reading_logs_via_rule_message/simple_request.cc
Labels: 3.x
