Repository owasp-modsecurity/ModSecurity, pull requests merged in 2024-10, with the labels that each got.

#3254 Leverage std::make_unique & std::make_shared to create objects in the heap
  headers/modsecurity/actions/action.h
  src/actions/expire_var.cc
  src/collection/backend/lmdb.cc
  src/operators/operator.cc
  src/run_time_string.cc
Labels: 3.x

#3267 chore: add 'log' action to rule 200005 (v2/master)
  modsecurity.conf-recommended
Labels: 2.x, config

#3279 Fixed PCRE2 error message
  apache2/msc_pcre.c
Labels: 2.x
